<li class="products__item">
            <p class="dispo">{{dispo}}</p>
            <img class="products__item__img" src="../assets/{{image}}" alt="">
            <h4 class="products__item__title">{{name}}</h4>
            <ul class="products__price">
                <li class="products__price-after">{{price}} €</li>
            </ul>
            <button data-id="{{id}}" class="products__item__btn">Voir le produit</button>
        </li>