 <div class="produit__select-item"><span>{{optionname_1}} :</span>
    <select class="produit__select" name="{{optionname_1}}">
        {{here1}}
    </select>
    <button class="pointer" type="submit" value="select-produit"><img src="../assets/select.svg"
    alt=""></button>
</div>
<div class="produit__select-item"><span>{{optionname_2}} :</span>
    <select class="produit__select" name="{{optionname_2}}">
        {{here2}}
    </select>
    <button class="pointer" type="submit" value="select-produit"><img src="../assets/select.svg"
    alt=""></button>
</div>